
KB = 1024
MB = (KB * KB)

PRINT_ALIGN_LEN = 48

STORAGE_TAB_SIZE = (4 * KB)
STORAGE_INFOPAGE_SIZE = STORAGE_TAB_SIZE 
STORAGE_RESERVE_SEC_SIZE = STORAGE_TAB_SIZE 

STORAGE_TAG = '[Storage]'

STORAGE_SLOT_HEADER = 0xEF0110FE
STORAGE_SLOT_ENDER = 0xFE1001EF

STORAGE_DEFAULTDATA = 0xFF
STORAGE_RESDATA = 0x55
